// Code generated by groq-modeler DO NOT EDIT.
//
// Created at: 2025-10-22 13:29:09
//
// groq-modeler Version 1.1.2

package groq

type (
	// Model is a ai model accessible through the groq api.
	Model string

	// ChatModel is the type for chat models present on the groq api.
	ChatModel Model

	// ModerationModel is the type for moderation models present on the groq api.
	ModerationModel Model

	// AudioModel is the type for audio models present on the groq api.
	AudioModel Model
)

var (
	// ModelAllam27B is an AI text chat model.
	//
	// It is created/provided by SDAIA.
	//
	// It has 4096 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelAllam27B ChatModel = "allam-2-7b"
	// ModelGroqCompound is an AI text chat model.
	//
	// It is created/provided by Groq.
	//
	// It has 131072 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelGroqCompound ChatModel = "groq/compound"
	// ModelGroqCompoundMini is an AI text chat model.
	//
	// It is created/provided by Groq.
	//
	// It has 131072 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelGroqCompoundMini ChatModel = "groq/compound-mini"
	// ModelLlama318BInstant is an AI text chat model.
	//
	// It is created/provided by Meta.
	//
	// It has 131072 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelLlama318BInstant ChatModel = "llama-3.1-8b-instant"
	// ModelLlama3370BVersatile is an AI text chat model.
	//
	// It is created/provided by Meta.
	//
	// It has 131072 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelLlama3370BVersatile ChatModel = "llama-3.3-70b-versatile"
	// ModelMetaLlamaLlama4Maverick17B128EInstruct is an AI text chat model.
	//
	// It is created/provided by Meta.
	//
	// It has 131072 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelMetaLlamaLlama4Maverick17B128EInstruct ChatModel = "meta-llama/llama-4-maverick-17b-128e-instruct"
	// ModelMetaLlamaLlama4Scout17B16EInstruct is an AI text chat model.
	//
	// It is created/provided by Meta.
	//
	// It has 131072 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelMetaLlamaLlama4Scout17B16EInstruct ChatModel = "meta-llama/llama-4-scout-17b-16e-instruct"
	// ModelMetaLlamaLlamaGuard412B is an AI text chat model.
	//
	// It is created/provided by Meta.
	//
	// It has 131072 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelMetaLlamaLlamaGuard412B ChatModel = "meta-llama/llama-guard-4-12b"
	// ModelMoonshotaiKimiK2Instruct is an AI text chat model.
	//
	// It is created/provided by Moonshot AI.
	//
	// It has 131072 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelMoonshotaiKimiK2Instruct ChatModel = "moonshotai/kimi-k2-instruct"
	// ModelMoonshotaiKimiK2Instruct0905 is an AI text chat model.
	//
	// It is created/provided by Moonshot AI.
	//
	// It has 262144 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelMoonshotaiKimiK2Instruct0905 ChatModel = "moonshotai/kimi-k2-instruct-0905"
	// ModelOpenaiGptOss120B is an AI text chat model.
	//
	// It is created/provided by OpenAI.
	//
	// It has 131072 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelOpenaiGptOss120B ChatModel = "openai/gpt-oss-120b"
	// ModelOpenaiGptOss20B is an AI text chat model.
	//
	// It is created/provided by OpenAI.
	//
	// It has 131072 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelOpenaiGptOss20B ChatModel = "openai/gpt-oss-20b"
	// ModelPlayaiTts is an AI text chat model.
	//
	// It is created/provided by PlayAI.
	//
	// It has 8192 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelPlayaiTts ChatModel = "playai-tts"
	// ModelPlayaiTtsArabic is an AI text chat model.
	//
	// It is created/provided by PlayAI.
	//
	// It has 8192 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelPlayaiTtsArabic ChatModel = "playai-tts-arabic"
	// ModelQwenQwen332B is an AI text chat model.
	//
	// It is created/provided by Alibaba Cloud.
	//
	// It has 131072 context window.
	//
	// It can be used with the following client methods:
	//	- ChatCompletion
	// 	- ChatCompletionStream
	// 	- ChatCompletionJSON
	ModelQwenQwen332B ChatModel = "qwen/qwen3-32b"
	// ModelMetaLlamaLlamaPromptGuard222M is an AI audio transcription model.
	//
	// It is created/provided by Meta.
	//
	// It has 512 context window.
	//
	// It can be used with the following client methods:
	//	- CreateTranscription
	// 	- CreateTranslation
	ModelMetaLlamaLlamaPromptGuard222M AudioModel = "meta-llama/llama-prompt-guard-2-22m"
	// ModelMetaLlamaLlamaPromptGuard286M is an AI audio transcription model.
	//
	// It is created/provided by Meta.
	//
	// It has 512 context window.
	//
	// It can be used with the following client methods:
	//	- CreateTranscription
	// 	- CreateTranslation
	ModelMetaLlamaLlamaPromptGuard286M AudioModel = "meta-llama/llama-prompt-guard-2-86m"
	// ModelWhisperLargeV3 is an AI audio transcription model.
	//
	// It is created/provided by OpenAI.
	//
	// It has 448 context window.
	//
	// It can be used with the following client methods:
	//	- CreateTranscription
	// 	- CreateTranslation
	ModelWhisperLargeV3 AudioModel = "whisper-large-v3"
	// ModelWhisperLargeV3Turbo is an AI audio transcription model.
	//
	// It is created/provided by OpenAI.
	//
	// It has 448 context window.
	//
	// It can be used with the following client methods:
	//	- CreateTranscription
	// 	- CreateTranslation
	ModelWhisperLargeV3Turbo AudioModel = "whisper-large-v3-turbo"
)
